# ********RoostGPT********

# Test generated by RoostGPT for test zbio-jan-3 using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929
# 
# Feature file generated for /example_get for http method type GET 
# RoostTestHash=2d7889707c
# 
# 

# ********RoostGPT********
Feature: Test /example endpoint with OAuth2 authentication

  Background:
    * def baseURL = karate.properties['SAMPLE_APPLICATION_FLOW_OAUTH2_PROJECT_BASE_URL'] || karate.properties['SAMPLE_APPLICATION_FLOW_OAUTH2_PROJECT_BASE_URL']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario: GET request to /example endpoint returns 200 OK
    Given path '/example'
    When method GET
    Then status 200
    And match responseHeaders['Content-Type'] contains 'application/json'

  Scenario: Verify response status code is 200
    Given path '/example'
    When method GET
    Then status 200
    And assert responseStatus == 200

  Scenario: Verify successful response with valid OAuth2 token
    Given path '/example'
    When method GET
    Then status 200
    And match responseType == 'json'

  Scenario: Verify authorization header is properly configured
    Given path '/example'
    When method GET
    Then status 200
    And match karate.prevRequest.headers['Authorization'] == '#(authToken)'
    And match karate.prevRequest.headers['Accept'] == 'application/json'
