# ********RoostGPT********

# Test generated by RoostGPT for test zbio-jan-3 using AI Type Claude AI and AI Model claude-sonnet-4-5-20250929
# 
# Feature file generated for /ping_get for http method type GET 
# RoostTestHash=628b0897a0
# 
# 

# ********RoostGPT********
Feature: Test /ping endpoint

Background:
  * def baseURL = karate.properties['SAMPLE_APPLICATION_FLOW_OAUTH2_PROJECT_BASE_URL'] || karate.properties['SAMPLE_APPLICATION_FLOW_OAUTH2_PROJECT_BASE_URL']
  * url baseURL
  * configure headers = { Accept: 'application/json' }

Scenario: Verify server heartbeat operation returns 200 OK
  Given path '/ping'
  When method GET
  Then status 200

Scenario: Verify server heartbeat operation with HEAD method
  Given path '/ping'
  When method HEAD
  Then status 200

Scenario: Verify response headers are present for ping endpoint
  Given path '/ping'
  When method GET
  Then status 200
  And match responseHeaders['content-type'] == '#present'

Scenario: Verify ping endpoint is accessible without authentication
  Given path '/ping'
  When method GET
  Then status 200

Scenario: Verify ping endpoint response time is acceptable
  Given path '/ping'
  When method GET
  Then status 200
  And assert responseTime < 5000
